nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: System
            description: System BP
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)